spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/taradiddle
jwt:
  access-token:
    secret-key: dGxmdGxya3Njb3hsZHhrZmtlbGVtZg==
    expiration: 25200000
  refresh-token:
    secret-key: cmVmcmVzaHRva2VudGFyYWRpZGRsZQ==
    expiration: 25200000
