spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/taradiddle?replicaSet=rs0
jwt:
  access-token:
    secret-key: dGxmdGxya3Njb3hsZHhrZmtlbGVtZg==
    expiration: 1800000
  refresh-token:
    secret-key: cmVmcmVzaHRva2VudGFyYWRpZGRsZQ==
    expiration: 604800000
