spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/taradiddle
jwt:
  secret-key: dGxmdGxya3Njb3hsZHhrZmtlbGVtZg==
  expiration: 25200000
