### 로그인
GET {{url}}/auth/login?userId=test@test.com&password=1234

### 회원가입
POST {{url}}/auth/sign-in
Content-Type: application/json

{
  "userId": "test@test.com",
  "password": "1234",
  "confirmPassword": "1234"
}
