### 로그인
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "hpotter@hogwarts.owl",
  "password": ""
}

### 회원가입
POST {{url}}/auth/sign-in
Content-Type: application/json

{
  "email": "hpotter@hogwarts.owl",
  "password": "",
  "confirmPassword": "",
  "username": "boltscar731",
  "firstName": "Harry",
  "lastName": "Potter"
}

### 로그인 갱신
POST {{url}}/auth/refresh
Content-Type: application/json
X-Refresh-Token:

{
  "email": "",
  "password": ""
}

### 로그아웃
DELETE {{url}}/auth/logout
Authorization: Bearer
X-USER-Id: 67cd4f215c36fa1542dd74d5
