### 로그인
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "hpotter@hogwarts.owl",
  "password": "boyWhoLived1234"
}

### 회원가입
POST {{url}}/auth/sign-in
Content-Type: application/json

{
  "email": "hpotter@hogwarts.owl",
  "password": "boyWhoLived1234",
  "confirmPassword": "boyWhoLived1234",
  "username": "boltscar731",
  "firstName": "Harry",
  "lastName": "Potter"
}

### 로그인 갱신
POST {{url}}/auth/refresh
Content-Type: application/json
X-Refresh-Token:

{
  "email": "",
  "password": ""
}

### 로그아웃
DELETE {{url}}/auth/logout/67f3df8ffea77a13964d946a
Authorization: Bearer

