### 로그인
POST {{url}}/auth/login
Content-Type: application/json

{
  "userId": "",
  "password": ""
}

### 회원가입
POST {{url}}/auth/sign-in
Content-Type: application/json

{
  "userId": "",
  "password": "",
  "confirmPassword": "",
  "username": "",
  "firstName": "",
  "lastName": ""
}

### 로그인 갱신
POST {{url}}/auth/refresh
Content-Type: application/json
X-Refresh-Token:

{
  "userId": "",
  "password": ""
}
