### 로그인
GET {{url}}/auth/login?userId=&password=

### 회원가입
POST {{url}}/auth/sign-in
Content-Type: application/json

{
  "userId": "",
  "password": "",
  "confirmPassword": "",
  "username": "iamGeorge",
  "firstName": "Fred",
  "lastName": "Weasley"
}
