### 친구 추가
PATCH {{url}}/friends/boltscar731
Content-Type: application/json
Authorization: Bearer

{
  "name": "plantLoverBoy"
}

### 친구 삭제
DELETE {{url}}/friends/boltscar731
Content-Type: application/json
Authorization: Bearer

{
  "name": "plantLoverBoy"
}
