### 유저 가져오기
GET {{url}}/users/67d6f5712fdecc025731c2e4
Authorization: Bearer

### 유저 생성
POST {{url}}/users
Content-Type: application/json
Authorization: Bearer

{
  "username": "",
  "firstName": "",
  "lastName": ""
}

### 유저 업데이트
PUT {{url}}/users
Content-Type: application/json
Authorization: Bearer

{
  "firstName": "harry",
  "lastName": "potter"
}

### 유저 삭제
DELETE {{url}}/users/boltscar731
Authorization: Bearer
