### 유저 가져오기
GET {{url}}/users/boltscar731
Authorization: Bearer

### 유저 생성
POST {{url}}/users
Content-Type: application/json
Authorization: Bearer

{
  "username": "plantLoverBoy",
  "firstName": "Neville",
  "lastName": "Longbottom"
}

### 유저 업데이트
PUT {{url}}/users
Content-Type: application/json
Authorization: Bearer

{
  "username": "BestChestKing1",
  "firstName": "Ron",
  "lastName": "Weasley"
}

### 유저 삭제
DELETE {{url}}/users/boltscar731
Authorization: Bearer
